plugins {
    id 'java-library'
    alias(libs.plugins.depman)
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:${libs.versions.spring.boot.get()}"
    }
}

dependencies {
    // JPA/Auditing (전이는 막기 위해 implementation 권장)
    implementation(libs.jakarta.persistence)     // ← api  ➜ implementation
    implementation(libs.spring.data.commons)     // ← api  ➜ implementation
    implementation(libs.spring.data.jpa)         // ← api  ➜ implementation
    implementation(libs.hibernate.core)


    // BaseEntity QueryDSL 메타모델 생성 + 컴파일을 위해 추가
    implementation(libs.querydsl.jpa)
    annotationProcessor("${libs.querydsl.apt.get()}:jakarta")
    annotationProcessor("jakarta.persistence:jakarta.persistence-api")
    annotationProcessor("jakarta.annotation:jakarta.annotation-api")

    compileOnly(libs.lombok)
    annotationProcessor(libs.lombok)

    // AutoConfiguration 지원
    implementation("org.springframework.boot:spring-boot-autoconfigure")

}
